/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CurriculumSelector: typeof import('./src/components/CurriculumSelector.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Introduction: typeof import('./src/components/Introduction.vue')['default']
    SubjectList: typeof import('./src/components/SubjectList.vue')['default']
  }
}
